adding channel get all
parkerholladay/node-octopus-deploy pull request #28
Opened 2019-10-07 20:52 UTC by pteyssedre

Hi,

Thanks for the nice work on the octopus-deploy ! I added the channel API call that I need for one of my project So I thought it could be useful to others

2019-10-14 16:13 UTC, parkerholladay commented on test/mocks/index.js
> +  ...require('./channel'),
Nit pick: Sort imports...

2019-10-14 16:15 UTC, parkerholladay requested changes
This is looking good. It looks like a `.tgz` file was committed that needs to be removed before we can merge. Also, if you wouldn't mind updating the `README` to include your new endpoint, that'd be great.

2019-10-14 16:23 UTC, parkerholladay commented
@pteyssedre Make sure that when you remove the `tgz` file, it isn't left in history either. Thanks for the PR.

2019-10-29 18:54 UTC, pteyssedre commented
I just have one question about the repo. I'm unable to run the test because of some errors due to  `AssertionError: expected file to have been called with arguments embrace/justice/tyrael.hots, { name: "tyrael.hots" }`

Is there anything I need to do to be able to run them properly ?

2019-11-05 18:12 UTC, parkerholladay commented
Sorry for not being very responsive. There isn't anything special needed to run tests other than installing dependencies, and running `npm test`. But, they seem to all be passing, and your new test is running fine.

2019-11-05 18:13 UTC, parkerholladay approved these changes

2019-11-05 18:13 UTC, parkerholladay approved these changes

2019-11-05 18:13 UTC, parkerholladay approved these changes

2019-11-05 18:13 UTC, parkerholladay approved these changes

2019-11-05 18:13 UTC, parkerholladay approved these changes

2019-11-05 18:16 UTC, parkerholladay commented
Rebased and merged, but github is experiencing issues. Closing PR.

2019-11-05 18:16 UTC, closed without merging